name: push

on:
  push:
    branches:
      - master
  pull_request:
     paths-ignore:
      - '**/*.md'
  release:
    types:
      - created
env:
  CHROME_BIN: "/usr/bin/google-chrome"
  NODE_ENV: test

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: mrdivyansh/eslint-action@1.0.7
        # GITHUB_TOKEN in forked repositories is read-only
        # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
        if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }} 
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          eslint-rc: .eslintrc.js
          execute-on-files:
            ./lib
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install dependencies
      run: npm ci
    - name: Create mongoDB Docker container
      run: sudo docker run -d -p 27017:27017 mongo:4.4.10-focal
    - name: run unit tests
      env:
        REPORTER: mocha-circleci-reporter
        MOCHA_FILE: junit/test-results.xml
      run: npm test
    #- name: coveralls
    #  run: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        # Name of the check run which will be created
        name: Unit Test report ${{ matrix.node-version }}
        path: junit/test-results.json
        reporter: mocha-json
    - name: Authenticate with registry
      if: github.event_name == 'release'
      run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
    - name: Publish package
      run: npm publish
